"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

export default function MaterialSettingsPage({ params }: { params: Promise<{ materialId: string }> }) {
  const [id, setId] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [duration, setDuration] = useState(60); const [pause, setPause] = useState(true); const [download, setDownload] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { params.then(async ({ materialId }) => { setId(materialId); const r = await fetch(`/api/materials/${materialId}`); const d = await r.json(); if (!r.ok) return setMessage(d.error ?? "Unable to load material"); const m = d.material; setTitle(m.title); setDescription(m.description ?? ""); setDuration(m.accessDurationMinutes); setPause(m.allowPause); setDownload(m.downloadEnabled); }); }, [params]);
  const save = async (e: React.FormEvent) => { e.preventDefault(); const r = await fetch(`/api/materials/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title.trim(), description: description.trim(), accessDurationMinutes: duration, allowPause: pause, downloadEnabled: download }) }); const d = await r.json(); setMessage(r.ok ? "Material settings saved." : d.error ?? "Unable to save settings"); };
  const archive = async () => { if (!window.confirm("Archive this material?")) return; const r = await fetch(`/api/materials/${id}`, { method: "DELETE" }); const d = await r.json(); if (r.ok) window.location.href = "/materials"; else setMessage(d.error ?? "Unable to archive material"); };
  return <main className="mx-auto min-h-screen max-w-2xl px-6 py-10"><Link href={`/materials/${id}`} className="muted text-sm">← Material</Link><h1 className="mt-3 text-3xl font-bold">Material settings</h1><form onSubmit={save} className="card mt-7 space-y-5 p-6"><input value={title} onChange={e => setTitle(e.target.value)} className="input" placeholder="Name" required /><textarea value={description} onChange={e => setDescription(e.target.value)} className="input min-h-28" placeholder="Description" /><div className="grid gap-4 sm:grid-cols-2"><label className="muted text-sm">Access minutes<input type="number" min="1" max="10080" value={duration} onChange={e => setDuration(Number(e.target.value))} className="input mt-2" /></label><label className="flex items-center gap-3 self-end pb-3"><input type="checkbox" checked={pause} onChange={e => setPause(e.target.checked)} />Allow pause</label></div><label className="flex items-center gap-3"><input type="checkbox" checked={download} onChange={e => setDownload(e.target.checked)} />Enable download</label><button className="w-full rounded-xl bg-violet-500 px-5 py-3 font-semibold">Save settings</button>{message && <p className="text-sm text-violet-300">{message}</p>}</form><button onClick={() => void archive()} className="mt-5 rounded-xl bg-rose-500/10 px-5 py-3 text-sm text-rose-300">Archive material</button></main>;
}
