import { and, eq } from "drizzle-orm";
import { db } from "@/db";
import { personalMaterials } from "@/db/schema";
import { requireUser } from "@/lib/auth/require-user";
import { createSignedFileUrl, removeStoredFile } from "@/lib/storage/supabase-storage";
import { z } from "zod";

const materialIdSchema=z.string().uuid();
export async function GET(_:Request,{params}:{params:Promise<{materialId:string}>}){try{const user=await requireUser();const materialId=materialIdSchema.parse((await params).materialId);const [material]=await db.select({id:personalMaterials.id,title:personalMaterials.title,description:personalMaterials.description,storageKey:personalMaterials.storageKey,originalFileName:personalMaterials.originalFileName,mimeType:personalMaterials.mimeType,fileSizeBytes:personalMaterials.fileSizeBytes,createdAt:personalMaterials.createdAt,updatedAt:personalMaterials.updatedAt}).from(personalMaterials).where(and(eq(personalMaterials.id,materialId),eq(personalMaterials.userId,user.id))).limit(1);if(!material)return Response.json({error:"Material not found"},{status:404});const signedUrl=await createSignedFileUrl(material.storageKey,true,300);return Response.json({material,signedUrl});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to load material"},{status:400});}}
export async function DELETE(_:Request,{params}:{params:Promise<{materialId:string}>}){try{const user=await requireUser();const materialId=materialIdSchema.parse((await params).materialId);const [material]=await db.select({storageKey:personalMaterials.storageKey}).from(personalMaterials).where(and(eq(personalMaterials.id,materialId),eq(personalMaterials.userId,user.id))).limit(1);if(!material)return Response.json({error:"Material not found"},{status:404});const [deleted]=await db.delete(personalMaterials).where(and(eq(personalMaterials.id,materialId),eq(personalMaterials.userId,user.id))).returning({id:personalMaterials.id});if(!deleted)return Response.json({error:"Material changed; please refresh"},{status:409});try{await removeStoredFile(material.storageKey,true);}catch(storageError){console.error("Personal study material storage cleanup failed:",storageError);}return Response.json({success:true});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to delete material"},{status:400});}}
