"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useState } from "react";

export default function MaterialUploadPage() {
  const search = useSearchParams(); const groupId = search.get("groupId") ?? ""; const [file, setFile] = useState<File | null>(null); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [visibility, setVisibility] = useState("group"); const [duration, setDuration] = useState("60"); const [pause, setPause] = useState(true); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!groupId) return setMessage("groupId is required."); if (!file) return setMessage("Choose a PDF first."); if (file.type !== "application/pdf") return setMessage("Only PDF files are supported."); setBusy(true); setMessage("Uploading…"); const form = new FormData(); form.append("file", file); form.append("groupId", groupId); const upload = await fetch("/api/materials/upload", { method: "POST", body: form }); const uploaded = await upload.json(); if (!upload.ok) { setBusy(false); return setMessage(uploaded.error ?? "Upload failed"); } const create = await fetch("/api/materials", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ groupId, title: title.trim() || file.name.replace(/\.pdf$/i, ""), description: description.trim(), visibility, availabilityMode: "immediate", accessDurationMinutes: Number(duration), allowPause: pause, downloadEnabled: false, expiryAction: "remove_access", storageKey: uploaded.storageKey, originalFileName: file.name, mimeType: file.type, fileSizeBytes: file.size, tags: [] }) }); const created = await create.json(); setBusy(false); if (!create.ok) return setMessage(created.error ?? "Unable to create material"); window.location.href = `/materials/${created.material.id}`; };
  return <main className="mx-auto min-h-screen max-w-2xl px-6 py-10"><Link href={groupId ? `/groups/${groupId}/materials` : "/materials"} className="muted text-sm">← Back</Link><h1 className="mt-3 text-3xl font-bold">Upload PDF</h1><form onSubmit={submit} className="card mt-7 space-y-5 p-6"><div><label className="muted text-sm">PDF file</label><input className="mt-2 block w-full text-sm" type="file" accept="application/pdf,.pdf" onChange={e => setFile(e.target.files?.[0] ?? null)} /></div><input value={title} onChange={e => setTitle(e.target.value)} className="input" placeholder="Material name" /><textarea value={description} onChange={e => setDescription(e.target.value)} className="input min-h-28" placeholder="Description" /><div className="grid gap-4 sm:grid-cols-2"><select value={visibility} onChange={e => setVisibility(e.target.value)} className="input"><option value="group">Group members</option><option value="public">Everyone</option></select><select value={duration} onChange={e => setDuration(e.target.value)} className="input"><option value="15">15 min</option><option value="30">30 min</option><option value="60">60 min</option><option value="120">120 min</option></select></div><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={pause} onChange={e => setPause(e.target.checked)} />Allow pause</label><button disabled={busy} className="w-full rounded-xl bg-violet-500 px-5 py-3 font-semibold disabled:opacity-50">{busy ? "Uploading…" : "Upload & publish"}</button>{message && <p className="text-sm text-violet-300">{message}</p>}</form></main>;
}
