"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

export default function MaterialViewerPage({ params }: { params: Promise<{ materialId: string }> }) {
  const [id, setId] = useState(""); const [url, setUrl] = useState(""); const [message, setMessage] = useState("Starting secure study session…"); const [seconds, setSeconds] = useState<number | null>(null);
  useEffect(() => { let timer: ReturnType<typeof setInterval> | undefined; params.then(async ({ materialId }) => { setId(materialId); const deviceId = localStorage.getItem("learn-league-device") || crypto.randomUUID(); localStorage.setItem("learn-league-device", deviceId); const start = await fetch(`/api/materials/${materialId}/access`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ deviceId }) }); const startData = await start.json(); if (!start.ok) return setMessage(startData.error ?? "Unable to start access"); const view = await fetch(`/api/materials/${materialId}/viewer?deviceId=${encodeURIComponent(deviceId)}`); const viewData = await view.json(); if (!view.ok) return setMessage(viewData.error ?? "Unable to open PDF"); setUrl(viewData.url); const initial = Math.max(0, Math.floor((new Date(startData.session.expiresAt).getTime() - Date.now()) / 1000)); setSeconds(initial); timer = setInterval(() => setSeconds(s => s === null ? null : Math.max(0, s - 1)), 1000); }); return () => { if (timer) clearInterval(timer); }; }, [params]);
  const pause = async () => { const deviceId = localStorage.getItem("learn-league-device") || ""; const r = await fetch(`/api/materials/${id}/access`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "pause", deviceId }) }); const d = await r.json(); setMessage(r.ok ? "Access paused." : d.error ?? "Unable to pause"); };
  const end = async () => { const deviceId = localStorage.getItem("learn-league-device") || ""; const r = await fetch(`/api/materials/${id}/access`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "end", deviceId }) }); const d = await r.json(); setMessage(r.ok ? "Study session ended." : d.error ?? "Unable to end session"); };
  const clock = seconds === null ? "--:--" : `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  return <main className="flex min-h-screen flex-col bg-black"><header className="flex items-center justify-between border-b border-white/10 px-4 py-3"><Link href={`/materials/${id}`} className="muted text-sm">← Material</Link><div className="rounded-full bg-violet-500/10 px-4 py-2 font-mono text-violet-300">{clock}</div><div className="flex gap-2"><button onClick={pause} className="rounded-lg bg-white/10 px-3 py-2 text-xs">Pause</button><button onClick={end} className="rounded-lg bg-rose-500/10 px-3 py-2 text-xs text-rose-300">End</button></div></header>{message !== "Starting secure study session…" && <p className="px-4 py-2 text-center text-xs text-violet-300">{message}</p>}{url ? <iframe title="Learn League PDF viewer" src={url} className="min-h-[calc(100vh-64px)] w-full flex-1 bg-white" /> : <div className="flex flex-1 items-center justify-center"><p className="muted">{message}</p></div>}</main>;
}
