"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

export default function GroupSettingsPage({ params }: { params: Promise<{ groupId: string }> }) {
  const [groupId, setGroupId] = useState(""); const [group, setGroup] = useState<any>(null); const [permissions, setPermissions] = useState<any[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { params.then(async ({ groupId }) => { setGroupId(groupId); const [g, p] = await Promise.all([fetch(`/api/groups/${groupId}`).then(r => r.json()), fetch(`/api/groups/${groupId}/permissions`).then(r => r.json())]); setGroup(g.group); setPermissions(p.permissions ?? []); }); }, [params]);
  const save = async (role: string, row: any) => { const r = await fetch(`/api/groups/${groupId}/permissions`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role, permissions: row }) }); setMessage(r.ok ? `${role} permissions saved.` : (await r.json()).error ?? "Unable to save permissions"); };
  const updateGroup = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); const r = await fetch(`/api/groups/${groupId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), description: data.get("description"), type: data.get("type"), visibility: data.get("visibility") }) }); const d = await r.json(); setMessage(r.ok ? "Group settings saved." : d.error ?? "Unable to save"); if (r.ok) setGroup(d.group); };
  if (!group) return <main className="p-10">Loading...</main>;
  return <main className="mx-auto min-h-screen max-w-4xl px-6 py-10"><Link href={`/groups/${groupId}`} className="muted text-sm">← Group</Link><h1 className="mt-3 text-3xl font-bold">Group settings</h1><form onSubmit={updateGroup} className="card mt-7 space-y-5 p-6"><input name="name" defaultValue={group.name} className="input" /><textarea name="description" defaultValue={group.description ?? ""} className="input min-h-24" /><div className="grid gap-4 sm:grid-cols-2"><select name="type" defaultValue={group.type} className="input"><option value="public">Public</option><option value="private">Private</option></select><select name="visibility" defaultValue={group.visibility} className="input"><option value="discoverable">Discoverable</option><option value="hidden">Hidden</option></select></div><button className="rounded-xl bg-violet-500 px-5 py-3 font-semibold">Save group</button></form><section className="mt-7"><h2 className="text-xl font-semibold">Role permissions</h2><div className="mt-4 space-y-4">{permissions.filter(p => p.role !== "owner").map(p => <div key={p.role} className="card p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold capitalize">{p.role.replace("_", " ")}</h3><button onClick={() => save(p.role, p)} className="rounded-lg bg-white/10 px-3 py-2 text-xs">Save</button></div><div className="grid gap-2 sm:grid-cols-2">{["manageMembers","manageMaterials","manageGroupInfo","manageInvitations","manageJoinRequests","manageContent"].map(key => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(p[key])} onChange={e => setPermissions(x => x.map(v => v.id === p.id ? { ...v, [key]: e.target.checked } : v))} />{key.replace(/^manage/, "Manage ")}</label>)}</div></div>)}</div></section>{message && <p className="mt-5 text-sm text-violet-300">{message}</p>}</main>;
}
