"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import OwnershipTransfer from "./ownership";

type Group = { id: string; name: string; description: string | null; type: string; visibility: string; ownerId: string };
type Permission = { id: string; role: string; manageMembers: boolean; manageMaterials: boolean; manageGroupInfo: boolean; manageInvitations: boolean; manageJoinRequests: boolean; manageContent: boolean };
const keys = ["manageMembers","manageMaterials","manageGroupInfo","manageInvitations","manageJoinRequests","manageContent"] as const;

export default function GroupSettingsPage({ params }: { params: Promise<{ groupId: string }> }) {
 const [groupId,setGroupId]=useState(""); const [group,setGroup]=useState<Group|null>(null); const [permissions,setPermissions]=useState<Permission[]>([]); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState("");
 useEffect(()=>{let cancelled=false;void params.then(async({groupId:id})=>{if(cancelled)return;setGroupId(id);try{const [gr,pr]=await Promise.all([fetch(`/api/groups/${id}`).then(r=>r.json()),fetch(`/api/groups/${id}/permissions`).then(r=>r.json())]);if(cancelled)return;setGroup(gr.group??null);setPermissions(pr.permissions??[]);if(!gr.group&&gr.error)setMessage(gr.error);if(pr.error&&!gr.group)setMessage(pr.error);}catch{if(!cancelled)setMessage("Unable to load settings.");}finally{if(!cancelled)setLoading(false);}});return()=>{cancelled=true;};},[params]);
 const save=async(role:string,row:Permission)=>{setSaving(role);try{const r=await fetch(`/api/groups/${groupId}/permissions`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({role,permissions:Object.fromEntries(keys.map(k=>[k,row[k]]))})});const d=await r.json();setMessage(r.ok?`${role.replace("_"," ")} permissions saved.`:d.error??"Unable to save permissions");}catch{setMessage("Unable to save permissions");}finally{setSaving("");}};
 const updateGroup=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving("group");const d=new FormData(e.currentTarget);try{const r=await fetch(`/api/groups/${groupId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:d.get("name"),description:d.get("description"),type:d.get("type"),visibility:d.get("visibility")})});const j=await r.json();setMessage(r.ok?"Group settings saved.":j.error??"Unable to save");if(r.ok)setGroup(j.group);}catch{setMessage("Unable to save group settings");}finally{setSaving("");}};
 const archive=async()=>{if(!window.confirm("Archive this group?"))return;setSaving("archive");try{const r=await fetch(`/api/groups/${groupId}`,{method:"DELETE"});if(r.ok)window.location.href="/groups";else{const d=await r.json();setMessage(d.error??"Unable to archive group");}}catch{setMessage("Unable to archive group");}finally{setSaving("");}};
 if(loading)return <main className="p-10">Loading settings…</main>;
 if(!group)return <main className="p-10"><p>{message||"Group not found."}</p><Link href="/groups" className="mt-3 inline-block text-violet-300">← Groups</Link></main>;
 return <main className="mx-auto min-h-screen max-w-4xl px-6 py-10"><Link href={`/groups/${groupId}`} className="muted text-sm">← Group</Link><h1 className="mt-3 text-3xl font-bold">Group settings</h1><form onSubmit={updateGroup} className="card mt-7 space-y-5 p-6"><input name="name" defaultValue={group.name} maxLength={100} className="input" required/><textarea name="description" defaultValue={group.description??""} maxLength={1000} className="input min-h-24"/><div className="grid gap-4 sm:grid-cols-2"><select name="type" defaultValue={group.type} className="input"><option value="public">Public</option><option value="private">Private</option></select><select name="visibility" defaultValue={group.visibility} className="input"><option value="discoverable">Discoverable</option><option value="hidden">Hidden</option></select></div><button disabled={saving!==""} className="rounded-xl bg-violet-500 px-5 py-3 font-semibold disabled:opacity-50">{saving==="group"?"Saving…":"Save group"}</button></form><section className="mt-8"><h2 className="text-xl font-semibold">Role permissions</h2><p className="muted mt-1 text-sm">Owner controls granular permissions; role hierarchy still applies.</p><div className="mt-4 space-y-4">{permissions.filter(p=>p.role!=="owner").map(p=><div key={p.id} className="card p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold capitalize">{p.role.replace("_"," ")}</h3><button disabled={saving!==""} onClick={()=>void save(p.role,p)} className="rounded-lg bg-white/10 px-3 py-2 text-xs disabled:opacity-50">{saving===p.role?"Saving…":"Save"}</button></div><div className="grid gap-3 sm:grid-cols-2">{keys.map(k=><label key={k} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(p[k])} onChange={e=>setPermissions(x=>x.map(v=>v.id===p.id?{...v,[k]:e.target.checked}:v))}/>{k.replace(/^manage/,"Manage ")}</label>)}</div></div>)}</div></section><OwnershipTransfer groupId={groupId}/><section className="card mt-7 border border-rose-500/20 p-6"><h2 className="font-semibold text-rose-300">Danger zone</h2><p className="muted mt-1 text-sm">Archive the group and remove it from active discovery.</p><button disabled={saving!==""} onClick={()=>void archive()} className="mt-4 rounded-xl bg-rose-500/10 px-4 py-3 text-sm text-rose-300 disabled:opacity-50">{saving==="archive"?"Archiving…":"Archive group"}</button></section>{message&&<p className="mt-5 text-sm text-violet-300">{message}</p>}</main>;
}
