import Link from "next/link";
import { requireUser } from "@/lib/auth/require-user";
import { getGroupMembership } from "@/lib/groups/membership";
import { db } from "@/db";
import { groups } from "@/db/schema";
import { eq } from "drizzle-orm";

export default async function GroupPage({ params }: { params: Promise<{ groupId: string }> }) {
  const user = await requireUser(); const { groupId } = await params; const [group] = await db.select().from(groups).where(eq(groups.id, groupId)).limit(1); const membership = await getGroupMembership(user.id, groupId);
  if (!group || !membership || group.status !== "active") return <main className="mx-auto max-w-3xl px-6 py-12"><p>Group not found or you are not a member.</p><Link href="/groups" className="mt-4 inline-block text-violet-300">← Back to groups</Link></main>;
  const canManage = membership.role !== "member";
  return <main className="mx-auto min-h-screen max-w-6xl px-6 py-10"><Link href="/groups" className="muted text-sm">← Groups</Link><div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="rounded-full bg-violet-500/10 px-3 py-1 text-xs capitalize text-violet-300">{group.type} · {membership.role.replace("_", " ")}</span><h1 className="mt-3 text-4xl font-bold">{group.name}</h1><p className="muted mt-2 max-w-2xl">{group.description || "Build your study routine together."}</p></div>{canManage && <Link href={`/groups/${groupId}/invite`} className="rounded-xl bg-violet-500 px-4 py-3 text-center font-semibold">Invite members</Link>}</div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Link href={`/groups/${groupId}/members`} className="card p-5 hover:bg-white/[0.06]"><p className="muted text-sm">Community</p><h2 className="mt-2 text-xl font-semibold">Members</h2><p className="muted mt-1 text-sm">Manage roles and membership.</p></Link><Link href={`/groups/${groupId}/materials`} className="card p-5 hover:bg-white/[0.06]"><p className="muted text-sm">Study library</p><h2 className="mt-2 text-xl font-semibold">Materials</h2><p className="muted mt-1 text-sm">Open your group PDFs.</p></Link>{canManage && <Link href={`/groups/${groupId}/requests`} className="card p-5 hover:bg-white/[0.06]"><p className="muted text-sm">Moderation</p><h2 className="mt-2 text-xl font-semibold">Join requests</h2><p className="muted mt-1 text-sm">Review pending requests.</p></Link>}{membership.role === "owner" && <Link href={`/groups/${groupId}/settings`} className="card p-5 hover:bg-white/[0.06]"><p className="muted text-sm">Control</p><h2 className="mt-2 text-xl font-semibold">Settings</h2><p className="muted mt-1 text-sm">Permissions and ownership.</p></Link>}{canManage && <Link href={`/groups/${groupId}/invite`} className="card p-5 hover:bg-white/[0.06]"><p className="muted text-sm">Access</p><h2 className="mt-2 text-xl font-semibold">Invitations</h2><p className="muted mt-1 text-sm">Codes and direct invitations.</p></Link>}</div></main>;
}
